[project]
name = "tp-deep-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dspy>=3.3.1",
    "ollama>=0.6.2",
]

[project.scripts]
tp-deep-learning = "tp_deep_learning:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
